import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DotPattern } from "@/components/magicui/dot-pattern";
import { Header } from "@/components/header";
import { cn } from "@/lib/utils";
import { Meteors } from "@/components/magicui/meteors";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="relative flex h-screen  w-full flex-col items-center justify-center overflow-hidden rounded-lg border bg-background">
          <Meteors />

          <DotPattern
            className={cn(
              "[mask-image:radial-gradient(1200px_circle_at_center,white,transparent)]",
            )}
          />

          {children}
          <Header />
        </div>
      </body>
    </html>
  );
}
